// ------------------------------------------------------------------------------
// <auto-generated>
// Code Generated by MySQLToCsharp
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MySQLToCsharpSampleConsoleApp
{
    /// <summary>
    /// USER TABLE
    /// </summary>
    public partial class Player
    {
        /// <summary>
        /// Player Id
        /// </summary>
        [Key]
        [Column(Order = 0)]
        public int Id { get; set; }
        public int Exp { get; set; }
    }
}
