name: dotnet-build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: dotnet build ./src/MySQLToCsharp.Parser/ -c Debug
      - run: dotnet build ./src/MySQLToCsharp -c Debug
      - run: dotnet test ./src/MySQLToCsharp.Tests/ -c Debug -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --test-adapter-path:. --logger:"xunit;LogFilePath=results.xml"
      - uses: codecov/codecov-action@v1
        with:
          file: ./src/MySQLToCsharp.Tests/coverage.net5.0.opencover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
