name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

jobs:
  build-dotnet:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: |
            5.0.x
            3.1.x
      - run: dotnet build -c Release -p:Version=${{ github.ref_name }}
      - run: dotnet pack -c Release -p:Version=${{ github.ref_name }} -o ./pack
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: nuget
          path: ./pack/
      # publish
      - run: dotnet publish ./src/MySQLToCsharp/ -c Release -o ./publish -f netcoreapp3.1 -r win-x64 -p:PublishSingleFile=true -p:Version=${{ github.ref_name }}
      - run: dotnet publish ./src/MySQLToCsharp/ -c Release -o ./publish -f netcoreapp3.1 -r linux-x64 -p:PublishSingleFile=true -p:Version=${{ github.ref_name }}
      - run: dotnet publish ./src/MySQLToCsharp/ -c Release -o ./publish -f netcoreapp3.1 -r osx-x64 -p:PublishSingleFile=true -p:Version=${{ github.ref_name }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: publish
          path: ./publish/
          retention-days: 1
          if-no-files-found: error

  create-release:
    needs: [build-dotnet]
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: 5.0.x
      # Create Release
      - name: Create Release
        uses: guitarrapc/actions/.github/actions/create-release@main
        with:
          tag: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset (Windows)
        run: gh release upload "${{ github.ref_name }}" MySQLToCsharp_win-x64_${{ github.ref_name }}.exe --clobber
        working-directory: publish/
      - name: Upload Release Asset (Linux)
        run: gh release upload "${{ github.ref_name }}" MySQLToCsharp_linux-x64_${{ github.ref_name }} --clobber
        working-directory: publish/
      - name: Upload Release Asset (macOS)
        run: gh release upload "${{ github.ref_name }}" MySQLToCsharp_osx-x64_${{ github.ref_name }} --clobber
        working-directory: publish/
      # upload nuget
      - run: dotnet nuget push "./nuget/*.nupkg" --skip-duplicate -k ${{ secrets.NUGET_KEY }}
